name: music-mix-analyzer

services:
  music-analyzer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-analyzer
    restart: unless-stopped
    ports:
      - "127.0.0.1:5001:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
      - GUNICORN_WORKERS=2
      - GUNICORN_THREADS=4
      - GUNICORN_TIMEOUT=300
      - GUNICORN_MAX_REQUESTS=1000
      - GUNICORN_MAX_REQUESTS_JITTER=50
      # Environment identification
      - RUN_ENV=docker
      # Security settings
      - FORCE_HTTPS=false
      - DOCKER_HAS_HTTPS=false
      # URL and domain settings
      - BASE_URL=http://localhost:5001
      - CANONICAL_DOMAIN=localhost:5001
      - USE_RELATIVE_URLS=true
      # Database connection for Docker
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=mixanalytic_db
      - MYSQL_PASSWORD=FH[@q#Z4YzQq1@8#
      - MYSQL_DATABASE=music_analyzer
      # OpenAI API settings - Pass these from .env file
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - AI_PROVIDER=${AI_PROVIDER:-openrouter}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL:-deepseek/deepseek-chat-v3-0324:free}
      - SITE_URL=${SITE_URL:-https://uygarduzgun.com}
      - SITE_TITLE=${SITE_TITLE:-Mix Analyzer}
      - OPENROUTER_TIMEOUT_THRESHOLD=${OPENROUTER_TIMEOUT_THRESHOLD:-30}
      # Visualization settings
      - SKIP_3D_VISUALIZATION=false
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./config:/app/config
    tmpfs:
      - /tmp:exec,size=1G
      - /dev/shm:size=2G
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

  db:
    image: mysql:8.0
    container_name: music-analyzer-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=music_analyzer
      - MYSQL_USER=mixanalytic_db
      - MYSQL_PASSWORD=FH[@q#Z4YzQq1@8#
    ports:
      - "127.0.0.1:3301:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --default-authentication-plugin=mysql_native_password --sql-mode="NO_ENGINE_SUBSTITUTION"
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE to avoid "mbind: Operation not permitted"

volumes:
  music_data:
    driver: local
  mysql_data:
    driver: local 